### ISSUE TITLE
Gif bug

### ISSUE THREAD

**Issue by casillaskhoren1** [pjchavarria/Aozora#122] opened 2016-04-25 09:03 UTC
When you tap on a gif to view it/save etc. the gif stops at the frame that it was showing when you tapped on it. Basically, it freezes when you tap on a gif.

**Comment by pjchavarria** [comment] 2016-04-28 07:11
Not a bug, since we're using a new way of displaying gifs the lightbox library don't support them out of the box, will need to use something else.

**Comment by pjchavarria** [comment] 2016-05-06 04:33
this was fixed on #105

**Closed by pjchavarria** 2016-05-06 04:33 UTC
Labels: required feature
