### ISSUE TITLE
Hour Differentiation

### ISSUE THREAD

**Issue by ToriFurukawa** [pjchavarria/Aozora#79] opened 2016-02-19 11:35 UTC
The certain amount of hours in which a post is sent differs from the amount of hours shown in the notifications. For example, a post from another user was actually sent 4 hours ago, but the notification said that it was sent one hour ago. Refreshing the page does nothing to change the number of hours in which the post or follow occured.

**Comment by sgript** [comment] 2016-02-19 12:07
Duplicate of #54.

**Closed by sgript** 2016-02-19 12:07 UTC
