### ISSUE TITLE
Crash bug 

### ISSUE THREAD

**Issue by Volrad** [pjchavarria/Aozora#74] opened 2016-02-18 15:59 UTC
App crashes whenever you try to enter another users library

**Comment by Volrad** [comment] 2016-02-18 16:08
![image](https://cloud.githubusercontent.com/assets/17318720/13149584/96475858-d627-11e5-89ab-e609a5f8b04e.png)

**Comment by sgript** [comment] 2016-02-18 20:11
Duplicate of #72

**Closed by sgript** 2016-02-18 20:11 UTC
