### ISSUE TITLE
Weird behavior when opening your library from your own profile page.

### ISSUE THREAD

**Issue by bigbenr** [pjchavarria/Aozora#126] opened 2016-04-28 20:37 UTC
I go there to see my stats (only way). When I'm in this page, tapping somewhere where's it's not one of my anime will open an anime page at random.
Also it seems that some lists are incomplete.
On iPad, the 2 latest builds (140 and 141)

**Comment by casillaskhoren1** [comment] 2016-04-28 20:43
It's also resulting crashes when you tap on the All Shows area on iPhone.

**Comment by pjchavarria** [comment] 2016-05-05 08:23
@bigbenr is this still happening to you?, i tested with 141 a while ago, couldn't reproduce it

**Comment by bigbenr** [comment] 2016-05-05 08:43
Yes it does, but only on iPad. I think it's a confusion between those 2 layouts. I'll take screencasts.

**Comment by bigbenr** [comment] 2016-05-05 09:00
Ok here's a screencast.
- In the classic library you can see that the first anime in the list in 12sai.
- In the library opened from my profile page this anime is gone.
- When I tap on the top left hand side (on the stat text), it opens the page of this same anime.
- When I tap on the top right hand side, it crashes the app. This crash bug wasn't present before build 146 btw.

Can't post movie on github, I'll try with slack.

**Comment by pjchavarria** [comment] 2016-05-05 23:36
thanks! fixed on #105

**Closed by pjchavarria** 2016-05-05 23:36 UTC
Labels: in review
