### ISSUE TITLE
Crashing when opening other's library

### ISSUE THREAD

**Issue by bigbenr** [pjchavarria/Aozora#141] opened 2016-05-08 09:39 UTC
When I open other people's library from their profile, the app crashes when trying to load the library.
Build 150 on iPad.

**Comment by P5YCH0DE** [comment] 2016-05-08 17:51
Also on 151

**Comment by pjchavarria** [comment] 2016-05-09 01:34
Can you give me an account example that is crashing? Can't reproduce it

**Comment by bigbenr** [comment] 2016-05-09 04:30
... can't reproduce it either now, on build 151. Not that I am complaining ! But apparently it happened on 151 for P5YCH0DE.

**Comment by P5YCH0DE** [comment] 2016-05-09 04:44
Try GirlyOtaku. Just random one that doesn't work.

**Comment by bigbenr** [comment] 2016-05-11 04:43
Oh, it happened again. And on multiple users (Umaru, Darkcirius, Bugs1415...). So it may be linked to bad loading instead of specific users.
The Aozora account doesn't produce this crash, and its library is empty so maybe there's a connection with the size (too big too load or something).

**Comment by pjchavarria** [comment] 2016-05-13 02:54
fixed on #148

**Closed by pjchavarria** 2016-05-13 02:54 UTC
Labels: in review
