### ISSUE TITLE
Can't open a follower up...sadly

### ISSUE THREAD

**Issue by P5YCH0DE** [pjchavarria/Aozora#143] opened 2016-05-08 17:34 UTC
When opening the menu of people following you, or people that you are following and trying to open one of those profiles, there will be no response.

**Comment by pjchavarria** [comment] 2016-05-09 01:43
can't reproduce it, can you give me any other clue?

**Comment by pjchavarria** [comment] 2016-05-13 02:40
fixed on #148

**Closed by pjchavarria** 2016-05-13 02:40 UTC
Labels: in review
